'use strict';
const INITIAL={"schema": 1, "versionLabel": "通用基础版", "profile": {"name": "你的姓名", "role": "目标岗位", "tagline": "意向城市｜到岗时间（请填写）", "gender": "", "birth": "", "phone": "", "email": "", "photo": "", "summary": "", "skills": "专业技能：填写与目标岗位相关的技能，并注明实际掌握程度。\n工具与协作：填写使用过的工具，以及你用它们完成的具体工作。", "education": [{"school": "学校名称", "major": "专业名称｜学历", "date": "入学时间—毕业时间", "description": "填写与岗位相关的课程、研究方向或学习成果。"}], "links": [{"label": "作品集／个人主页", "url": ""}]}, "work": [{"id": "work-1", "name": "公司／组织名称", "role": "岗位名称", "date": "起止时间", "bullets": "本人职责：填写负责的任务、覆盖的范围与交付要求。\n工作成果：填写实际完成的交付物；有可核验的数据时补充数据。", "url": "", "enabled": true}], "campus": [], "awards": [], "projects": [{"id": "project-1", "name": "项目名称", "role": "本人角色", "date": "起止时间", "bullets": "职责与行动：围绕项目目标，写清自己负责的部分及采取的行动。\n项目成果：说明交付内容、完成状态与验证方式，附上可公开的作品链接。", "url": "", "enabled": true}], "experiencePresets": [{"id": "general", "name": "通用实践", "text": "相关实践：填写与目标岗位相关的实践经历，说明任务、行动和结果。\n持续学习：填写已完成的课程、练习或证书，以及对应的实际应用。"}, {"id": "product", "name": "产品／运营", "text": "用户与需求：填写实际参与的需求分析、用户访谈或资料整理工作。\n运营与复盘：填写活动执行、内容运营或数据复盘的具体经历。"}, {"id": "engineering", "name": "技术／工程", "text": "开发实践：填写实际使用的语言、工具与完成的功能。\n质量与协作：填写问题定位、测试验证、代码维护或团队协作的实际经历。"}], "activeExperience": "general", "casePresets": [{"id": "general", "name": "通用案例", "title": "案例名称｜分析主题", "url": "", "text": "背景与目标：说明分析对象、问题范围和使用的材料。\n分析与产出：写出关键发现、自己的判断及最终产出，并标明验证情况。"}, {"id": "product", "name": "产品／运营案例", "title": "产品／业务名称｜专题分析", "url": "", "text": "分析范围：填写目标用户、使用场景及需要解决的问题。\n结论与建议：根据实际材料写出判断、改进建议和验证计划。"}, {"id": "engineering", "name": "技术／质量案例", "title": "系统／功能名称｜问题分析", "url": "", "text": "问题与定位：说明问题表现、复现条件和定位过程。\n方案与验证：说明方案取舍、完成的修改及验证结果。"}], "activeCase": "general", "showCase": true, "style": {"theme": "#137e8d", "font": 12, "leading": 1.55, "gap": 12, "layout": "plain", "family": "Noto Sans SC", "margin": 36, "singleTemplate": "line"}, "modules": [{"id": "education", "title": "教育背景", "enabled": true}, {"id": "work", "title": "实习／工作经历", "enabled": true}, {"id": "projects", "title": "项目经历", "enabled": true}, {"id": "cases", "title": "案例分析", "enabled": true}, {"id": "skills", "title": "专业能力", "enabled": true}, {"id": "experience", "title": "专业实践", "enabled": false}, {"id": "campus", "title": "校园经历", "enabled": false}, {"id": "awards", "title": "获奖经历", "enabled": false}, {"id": "links", "title": "补充链接", "enabled": false}, {"id": "summary", "title": "个人总结", "enabled": false}], "versions": []};
let renderForm=()=>{},renderResume=()=>{};
const KEY='mhwangzi-resume-workbench-v1-'+(document.documentElement.dataset.store||'main');
const clone=x=>JSON.parse(JSON.stringify(x));
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=s=>{try{const u=new URL(s);return ['http:','https:','mailto:'].includes(u.protocol)?u.href:''}catch{return ''}};
const photoUrl=s=>/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(s)?s:'';
const lines=s=>String(s).split('\n').map(x=>x.trim()).filter(Boolean);
let data=clone(INITIAL),tab='basic',zoom='auto',toastTimer;
function validate(x){if(!x||x.schema!==1||!x.profile||typeof x.profile.name!=='string'||!Array.isArray(x.projects)||!Array.isArray(x.experiencePresets)||!Array.isArray(x.casePresets)||!x.experiencePresets.length||!x.casePresets.length||!Array.isArray(x.versions)||!x.style||!Array.isArray(x.profile.education)||!Array.isArray(x.profile.links))throw Error('材料格式不正确');const strings=(o,keys)=>keys.every(k=>typeof o[k]==='string');if(!strings(x.profile,['role','tagline','phone','email','photo','skills'])||!x.profile.education.every(o=>strings(o,['school','major','date']))||!x.profile.links.every(o=>strings(o,['label','url']))||!x.projects.every(o=>strings(o,['id','name','date','role','url','bullets']))||!x.experiencePresets.every(o=>strings(o,['id','name','text']))||!x.casePresets.every(o=>strings(o,['id','name','title','text','url']))||!x.experiencePresets.some(o=>o.id===x.activeExperience)||!x.casePresets.some(o=>o.id===x.activeCase)||!/^#[0-9a-f]{6}$/i.test(x.style.theme)||![x.style.font,x.style.leading,x.style.gap].every(Number.isFinite)||x.style.font<9||x.style.font>16||x.style.leading<1.2||x.style.leading>2.2||x.style.gap<8||x.style.gap>30||!['colorblock','plain'].includes(x.style.layout)||!x.versions.every(v=>strings(v,['name','id','date'])&&v.doc))throw Error('材料字段缺失或格式不正确');return x;}
try{const embedded=JSON.parse($('#embedded-state').textContent);const saved=localStorage.getItem(KEY);data=validate(saved?JSON.parse(saved):embedded||clone(INITIAL));}catch(e){data=clone(INITIAL);setTimeout(()=>toast('已载入初始材料；未覆盖无法读取的旧备份。'),100);}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',3300);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));$('#saveStatus').textContent='已保存到本机 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});}catch{$('#saveStatus').textContent='本机保存失败，请下载备份';}renderResume();}
function setPath(path,value){let o=data;const ks=path.split('.');ks.slice(0,-1).forEach(k=>o=o[k]);o[ks.at(-1)]=value;save();}
function field(label,path,value,type='text',rows=3){return `<label class="field">${esc(label)}${type==='textarea'?`<textarea data-path="${path}" rows="${rows}">${esc(value)}</textarea>`:`<input data-path="${path}" type="${type}" value="${esc(value)}">`}</label>`;}
function selectedExperience(){return data.experiencePresets.find(x=>x.id===data.activeExperience);}
function selectedCase(){return data.casePresets.find(x=>x.id===data.activeCase);}
function richLine(s){const i=s.indexOf('：');return i>0&&i<18?'<strong>'+esc(s.slice(0,i+1))+'</strong>'+esc(s.slice(i+1)):esc(s);}
function link(url,label,cls=''){const s=safeUrl(url);return s?`<a href="${esc(s)}" target="_blank" rel="noopener noreferrer" class="${cls}">${esc(label)}</a>`:esc(label);}
function sizePreview(){const r=$('#resume'),w=$('#paperWrap'),space=$('.paper-space');const z=zoom==='auto'?Math.min(1,Math.max(.25,(space.clientWidth-4)/794)):Number(zoom);r.style.transform=`scale(${z})`;w.style.width=(r.offsetWidth*z)+'px';w.style.height=(r.offsetHeight*z)+'px';const over=r.offsetHeight>1124;$('#pageStatus').textContent=over?'内容超过一页 · 请精简或调整版式':'当前内容可容纳于1页A4';$('#pageStatus').className=over?'overflow':'';}
function uid(){return Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);}
function renderVersions(){const v=$('#versions'),old=v.value;v.innerHTML='<option value="">选择已保存版本</option>'+data.versions.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} · ${esc(x.date)}</option>`).join('');v.value=old;}
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),15000);}
const filename=()=>data.profile.name+'_'+($('#versionName').value.trim()||'简历')+'_'+new Date().toLocaleDateString('sv-SE');
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));renderForm();$('.editor').scrollTop=0;});
$('#zoom').onchange=e=>{zoom=e.target.value;sizePreview();};$('#fit').onclick=()=>{zoom='auto';$('#zoom').value='auto';sizePreview();};window.addEventListener('resize',sizePreview);
$('#saveVersion').onclick=()=>{const name=$('#versionName').value.trim();if(!name){$('#versionName').focus();return toast('先填写公司或版本名称');}const doc=clone(data);doc.versions=[];const v={id:uid(),name,date:new Date().toLocaleDateString('sv-SE'),doc};data.versions.push(v);save();renderVersions();$('#versions').value=v.id;toast('已另存版本，当前材料仍可继续修改');};
$('#loadVersion').onclick=()=>{const v=data.versions.find(x=>x.id===$('#versions').value);if(!v)return toast('请选择已保存版本');try{const next=validate(clone(v.doc));const versions=data.versions;const before=clone(data);before.versions=[];versions.push({id:uid(),name:'载入前自动备份',date:new Date().toLocaleDateString('sv-SE'),doc:before});data=next;data.versions=versions;data.versionLabel=v.name;$('#versionName').value=v.name;save();renderForm();renderVersions();toast('已载入版本；载入前内容保留在自动备份中');}catch{toast('此版本内容不完整，未载入');}};
$('#backup').onclick=()=>download(filename()+'_全部材料.json',JSON.stringify(data,null,2),'application/json');
$('#import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>20000000)throw Error('文件过大');const x=validate(JSON.parse(await f.text()));const before=clone(data);before.versions=[];x.versions.push({id:uid(),name:'导入前自动备份',date:new Date().toLocaleDateString('sv-SE'),doc:before});data=x;save();renderForm();renderVersions();toast('已导入，原内容保留在自动备份中');}catch{toast('文件格式不正确，原材料未改动');}e.target.value='';};
$('#print').onclick=()=>{$('#printWarning').textContent=$('#resume').offsetHeight>1124?'当前内容超过一页，建议先调整版式或精简内容。':'';$('#exportHelp').showModal();};$('#cancelPrint').onclick=()=>$('#exportHelp').close();$('#browserPrint').onclick=()=>{$('#exportHelp').close();document.title=filename();window.print();};$('#confirmPrint').onclick=async()=>{if($('#resume').offsetHeight>1124){toast('直接下载支持一页，请先调整版式；多页可用浏览器打印');return;}try{const bytes=await resumePdf($('#resume'));download(filename()+'.pdf',bytes,'application/pdf');$('#exportHelp').close();toast('PDF已生成，保留文字和链接');}catch(e){toast('直接导出失败，可使用浏览器打印');}};
$('#versionName').value=data.versionLabel||'';$('#versionName').oninput=()=>{data.versionLabel=$('#versionName').value;save();};renderForm();renderVersions();renderResume();